var namespace_fifty_one_1_1_device_detection_1_1_examples_1_1_on_premise_1_1_update_data_file =
[
    [ "CompletionListener", "class_fifty_one_1_1_device_detection_1_1_examples_1_1_on_premise_1_1_update_data_file_1_1_completion_listener.html", "class_fifty_one_1_1_device_detection_1_1_examples_1_1_on_premise_1_1_update_data_file_1_1_completion_listener" ],
    [ "Program", "class_fifty_one_1_1_device_detection_1_1_examples_1_1_on_premise_1_1_update_data_file_1_1_program.html", "class_fifty_one_1_1_device_detection_1_1_examples_1_1_on_premise_1_1_update_data_file_1_1_program" ]
];