# No push trigger. However, by default without PR trigger specified,
# this is run when a PR is created.
trigger: none

# Schedule to run overnight
schedules:
- cron: "0 20 * * *"
  displayName: Daily overnight build
  branches:
    include:
    - develop

# Use shared variables
variables:
- template: shared-variables.yml

stages:
- template: shared-build-and-test-stage.yml
  parameters:
    imageName: $(imageName)
    nugetVersion: $(nugetVersion)
