# Debug build is only needed for investigating issues so should be manually triggered only
trigger: none

# Don't trigger for a pull request.
pr: none

resources:
  repositories:
    - repository: ciTemplates # Id of the repository used to reference to in this script
      type: git
      name: common-ci # Name of the actual repository

# Use shared variables
variables:
- template: shared-variables.yml
- template: shared-variables.yml@ciTemplates

# Perform build, test and create packages
stages:
# Build source and create packages
- template: shared-create-packages-stage.yml
  parameters:
    nugetVersion: $(nugetVersion)
    imageName: $(windowsImageDD)
    linuxImage: $(linuxImage)
    targetPublishConfig: 'Debug'
    templates: 'ciTemplates'
