/* *********************************************************************
 * This Original Work is copyright of 51 Degrees Mobile Experts Limited.
 * Copyright 2023 51 Degrees Mobile Experts Limited, Davidson House,
 * Forbury Square, Reading, Berkshire, United Kingdom RG1 3EU.
 *
 * This Original Work is licensed under the European Union Public Licence
 * (EUPL) v.1.2 and is subject to its terms as set out below.
 *
 * If a copy of the EUPL was not distributed with this file, You can obtain
 * one at https://opensource.org/licenses/EUPL-1.2.
 *
 * The 'Compatible Licences' set out in the Appendix to the EUPL (as may be
 * amended by the European Commission) shall be deemed incompatible for
 * the purposes of the Work and the provisions of the compatibility
 * clause in Article 5 of the EUPL shall not apply.
 * 
 * If using the Work as, or as part of, a network application, by 
 * including the attribution notice(s) required under Article 5 of the EUPL
 * in the end user terms of the application under an appropriate heading, 
 * such notice(s) shall fulfill the requirements of that article.
 * ********************************************************************* */

/* *********************************************************************
 * This code is auto generated by 51Degrees using the most up to data
 * at the time of release, and should not be changed directly.
 * **********************************************************************/
using FiftyOne.Pipeline.Core.Data.Types;
using FiftyOne.Pipeline.Engines.Data;
using System.Collections.Generic;

// This interface sits at the top of the name space in order to make 
// life easier for consumers.
namespace FiftyOne.DeviceDetection
{
	/// <summary>
	/// Represents a data object containing values relating to a device.
	/// This includes the hardware, operating system and browser as
	/// well as crawler details if the request actually came from a 
	/// bot or other automated system.
	/// </summary>
	public interface IDeviceData : IAspectData
	{
		/// <summary>
		/// Indicates what ajax request format should be used.
		/// </summary>
		IAspectPropertyValue<string> AjaxRequestType { get; }
		/// <summary>
		/// Indicates if the browser supports 'window.requestAnimationFrame()' method.
		/// </summary>
		IAspectPropertyValue<bool> AnimationTiming { get; }
		/// <summary>
		/// Indicates the resolution of the device's back camera in megapixels. For a device that has a rotating camera the same value is returned for front and back megapixels properties.
		/// </summary>
		IAspectPropertyValue<double> BackCameraMegaPixels { get; }
		/// <summary>
		/// Indicates the capacity of the device's standard battery in mAh. This property is not applicable for a device that does not have a battery.
		/// </summary>
		IAspectPropertyValue<int> BatteryCapacity { get; }
		/// <summary>
		/// Indicates the number of bits used to describe the colour of each individual pixel, also known as bit depth or colour depth.
		/// </summary>
		IAspectPropertyValue<int> BitsPerPixel { get; }
		/// <summary>
		/// Indicates if the browser fully supports BlobBuilder, containing a BlobBuilder interface, a FileSaver interface, a FileWriter interface, and a FileWriterSync interface.
		/// </summary>
		IAspectPropertyValue<bool> BlobBuilder { get; }
		/// <summary>
		/// Refers to the list of audio codecs in specific formats supported for Decode by the Web Browser. This list of codecs is supported for playback on a basic browser installation.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> BrowserAudioCodecsDecode { get; }
		/// <summary>
		/// Refers to the list of audio codecs in specific formats supported for Encode by the Web Browser. This list of codecs is supported for capture on a basic browser installation.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> BrowserAudioCodecsEncode { get; }
		/// <summary>
		/// Indicates the age in months of the browser since the BrowserDiscontinuedYear and BrowserDiscontinuedMonth.
		/// </summary>
		IAspectPropertyValue<int> BrowserDiscontinuedAge { get; }
		/// <summary>
		/// The month in which further development of the browser version is stopped by the browser vendor. This occurs when a new stable version of the browser is released.
		/// </summary>
		IAspectPropertyValue<string> BrowserDiscontinuedMonth { get; }
		/// <summary>
		/// The year in which further development of the browser version is stopped by the browser vendor. This occurs when a new stable version of the browser is released.
		/// </summary>
		IAspectPropertyValue<int> BrowserDiscontinuedYear { get; }
		/// <summary>
		/// Indicates the name of the browser without the default OS or layout engine.
		/// </summary>
		IAspectPropertyValue<string> BrowserFamily { get; }
		/// <summary>
		/// Indicates the name of the browser. Many mobile browsers, by default, come with an operating system (OS). Unless specifically named, these browsers are named after the accompanying OS and/or the layout engine. 
		/// </summary>
		IAspectPropertyValue<string> BrowserName { get; }
		/// <summary>
		/// Indicates the age in months of the browser since the BrowserPreviewYear and BrowserPreviewMonth.
		/// </summary>
		IAspectPropertyValue<int> BrowserPreviewAge { get; }
		/// <summary>
		/// The month in which the browser version is originally released as a Beta/Developer version by the browser vendor. This is before it is officially released as a stable version, to ensure wider testing by the community can take place.
		/// </summary>
		IAspectPropertyValue<string> BrowserPreviewMonth { get; }
		/// <summary>
		/// The year in which the browser version is originally released as a Beta/Developer version by the browser vendor. This is before it is officially released as a stable version, to ensure wider testing by the community can take place.
		/// </summary>
		IAspectPropertyValue<int> BrowserPreviewYear { get; }
		/// <summary>
		/// Indicates the source from which browser properties have been validated. Primary browser data are retrieved from the internal test and populated manually, then they might be validated against an external source such as Caniuse or RingMark. 
		/// </summary>
		IAspectPropertyValue<string> BrowserPropertySource { get; }
		/// <summary>
		/// A measure of the popularity of this browser version. All browsers are ordered by the number of events associated with that browser that occurred in the sampling period. The browser with the most events is ranked 1, the second 2 and so on.
		/// </summary>
		IAspectPropertyValue<int> BrowserRank { get; }
		/// <summary>
		/// Indicates the age in months of the browser since the BrowserReleaseYear and BrowserReleaseMonth.
		/// </summary>
		IAspectPropertyValue<int> BrowserReleaseAge { get; }
		/// <summary>
		/// The month in which the browser version is officially released to users by the browser vendor. This version is called the stable version as any bugs or difficulties highlighted in the Beta/Developer Version will have been fixed for this release.
		/// </summary>
		IAspectPropertyValue<string> BrowserReleaseMonth { get; }
		/// <summary>
		/// The year in which the browser version is officially released to users by the browser vendor. This version is called the stable version as any bugs or difficulties highlighted in the Beta/Developer Version will have been fixed for this release.
		/// </summary>
		IAspectPropertyValue<int> BrowserReleaseYear { get; }
		/// <summary>
		/// Indicates the name of the company which created the browser.
		/// </summary>
		IAspectPropertyValue<string> BrowserVendor { get; }
		/// <summary>
		/// Indicates the version or subversion of the browser.
		/// </summary>
		IAspectPropertyValue<string> BrowserVersion { get; }
		/// <summary>
		/// Refers to the list of video codecs in specific formats supported for Decode by the Web Browser. This list of codecs is supported for playback on a basic browser installation.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> BrowserVideoCodecsDecode { get; }
		/// <summary>
		/// Refers to the list of video codecs in specific formats supported for Encode by the Web Browser. This list of codecs is supported for capture on a basic browser installation.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> BrowserVideoCodecsEncode { get; }
		/// <summary>
		/// Indicates the list of camera types the device has. If the device has a rotating camera, this property refers to both front and back facing cameras.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> CameraTypes { get; }
		/// <summary>
		/// Indicates if the browser supports the canvas element, useful for drawing graphics via scripting (usually JavaScript).
		/// </summary>
		IAspectPropertyValue<bool> Canvas { get; }
		/// <summary>
		/// Stands for Composite Capability/Preference Profiles.  Refers to the list of MIME types supported by the operating system. The list does not include MIME types that are only enabled through the use of 3rd party applications.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> CcppAccept { get; }
		/// <summary>
		/// Indicates which version of the Connected Limited Device Configuration the device supports for use with Java ME.
		/// </summary>
		IAspectPropertyValue<double> CLDC { get; }
		/// <summary>
		/// Indicates the contrast ratio of the device. This property is applicable only for TVs.
		/// </summary>
		IAspectPropertyValue<string> ContrastRatio { get; }
		/// <summary>
		/// Indicates if the browser supports http Cookies. However, the user may have disabled Cookies in their own configuration. Where data cannot be validated, it is assumed that the browser supports cookies.
		/// </summary>
		IAspectPropertyValue<bool> CookiesCapable { get; }
		/// <summary>
		/// Indicates the official name of the CPU within the SoC, e.g. ARM Cortex A9 or Krait (Qualcomm).
		/// </summary>
		IAspectPropertyValue<string> CPU { get; }
		/// <summary>
		/// Indicates the number of physical CPU cores the device has.
		/// </summary>
		IAspectPropertyValue<int> CPUCores { get; }
		/// <summary>
		/// Indicates the Semiconductor Company that designed the CPU.
		/// </summary>
		IAspectPropertyValue<string> CPUDesigner { get; }
		/// <summary>
		/// Indicates the maximum frequency of the CPU of the device in gigahertz (GHz).
		/// </summary>
		IAspectPropertyValue<double> CPUMaximumFrequency { get; }
		/// <summary>
		/// Indicates the crawler name when applicable. Returns NotCrawler when the device is not a crawler.
		/// </summary>
		IAspectPropertyValue<string> CrawlerName { get; }
		/// <summary>
		/// Indicates if the browser supports CSS3 background properties (such as background-image, background-color, etc.) that allow styling of the border and the background of an object, and create a shadow effect.
		/// </summary>
		IAspectPropertyValue<bool> CssBackground { get; }
		/// <summary>
		/// Indicates if the browser supports border images, allowing decoration of the border around an object.
		/// </summary>
		IAspectPropertyValue<bool> CssBorderImage { get; }
		/// <summary>
		/// Indicates if the browser can draw CSS images into a Canvas.
		/// </summary>
		IAspectPropertyValue<bool> CssCanvas { get; }
		/// <summary>
		/// Indicates if the browser supports CSS3 Color, allowing author control of the foreground colour and opacity of an element.
		/// </summary>
		IAspectPropertyValue<bool> CssColor { get; }
		/// <summary>
		/// Indicates if the browser supports CSS3 columns for setting column- width and column-count.
		/// </summary>
		IAspectPropertyValue<bool> CssColumn { get; }
		/// <summary>
		/// Indicates if the browser supports flexbox, allowing the automatic reordering of elements on the page when accessed from devices with different screen sizes.
		/// </summary>
		IAspectPropertyValue<bool> CssFlexbox { get; }
		/// <summary>
		/// Indicates if the browser supports CSS3 fonts, including non-standard fonts, e.g. @font-face.
		/// </summary>
		IAspectPropertyValue<bool> CssFont { get; }
		/// <summary>
		/// Indicates if the browser supports all CSS grid properties.
		/// </summary>
		IAspectPropertyValue<bool> CssGrid { get; }
		/// <summary>
		/// Indicates if the browser supports CSS3 images, allowing for fall-back images, gradients and other effects.
		/// </summary>
		IAspectPropertyValue<bool> CssImages { get; }
		/// <summary>
		/// Indicates if the browser supports MediaQueries for dynamic CSS that uses the @media rule.
		/// </summary>
		IAspectPropertyValue<bool> CssMediaQueries { get; }
		/// <summary>
		/// Indicates if the browser supports the CSS 'min-width' and 'max-width' element.
		/// </summary>
		IAspectPropertyValue<bool> CssMinMax { get; }
		/// <summary>
		/// Indicates if the browser supports overflowing of clipped blocks.
		/// </summary>
		IAspectPropertyValue<bool> CssOverflow { get; }
		/// <summary>
		/// Indicates if the browser supports CSS position, allowing for different box placement algorithms, e.g. static, relative, absolute, fixed and initial.
		/// </summary>
		IAspectPropertyValue<bool> CssPosition { get; }
		/// <summary>
		/// Indicates if the browser supports all CSS3 text features including: text-overflow, word-wrap and word-break.
		/// </summary>
		IAspectPropertyValue<bool> CssText { get; }
		/// <summary>
		/// Indicates if the browser supports 2D transformations in CSS3 including rotating, scaling, etc. This property includes support for both transform and transform-origin properties.
		/// </summary>
		IAspectPropertyValue<bool> CssTransforms { get; }
		/// <summary>
		/// Indicates if the browser supports CSS3 transitions elements, used for animating changes to properties.
		/// </summary>
		IAspectPropertyValue<bool> CssTransitions { get; }
		/// <summary>
		/// Indicates if the browser supports CSS UI stylings, including text-overflow, css3-boxsizing and pointer properties.
		/// </summary>
		IAspectPropertyValue<bool> CssUI { get; }
		/// <summary>
		/// Indicates if the browser has the ability to embed custom data attributes on all HTML elements using the 'data-' prefix.
		/// </summary>
		IAspectPropertyValue<bool> DataSet { get; }
		/// <summary>
		/// Indicates if the browser allows encoded data to be contained in a URL.
		/// </summary>
		IAspectPropertyValue<bool> DataUrl { get; }
		/// <summary>
		/// Indicates what certifications apply to this device.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> DeviceCertifications { get; }
		/// <summary>
		/// Consists of four components separated by a hyphen symbol: Hardware-Platform-Browser-IsCrawler where each Component represents an ID of the corresponding Profile.
		/// </summary>
		IAspectPropertyValue<string> DeviceId { get; }
		/// <summary>
		/// Indicates if the browser supports DOM events for device orientation, e.g. 'deviceorientation', 'devicemotion' and 'compassneedscalibration'.
		/// </summary>
		IAspectPropertyValue<bool> DeviceOrientation { get; }
		/// <summary>
		/// Indicates the maximum volatile RAM capacity of the device in megabytes (MB). Where a device has different RAM capacity options, the largest option available is returned.
		/// </summary>
		IAspectPropertyValue<int> DeviceRAM { get; }
		/// <summary>
		/// Indicates the volatile RAM capacity options for the device in megabytes (MB). If no variants are found, then the value returned will be the same as "DeviceRAM".
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> DeviceRAMVariants { get; }
		/// <summary>
		/// Indicates the type of the device based on values set in other properties, such as IsMobile, IsTablet, IsSmartphone, IsSmallScreen etc.
		/// </summary>
		IAspectPropertyValue<string> DeviceType { get; }
		/// <summary>
		/// Used when detection method is not Exact or None. This is an integer value and the larger the value the less confident the detector is in this result.
		/// </summary>
		IAspectPropertyValue<int> Difference { get; }
		/// <summary>
		/// Total difference in character positions where the substrings hashes were found away from where they were expected.
		/// </summary>
		IAspectPropertyValue<int> Drift { get; }
		/// <summary>
		/// Indicates the device's Ingress Protection Rating against dust and water (http://en.wikipedia.org/wiki/IP_Code).
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> Durability { get; }
		/// <summary>
		/// Indicates the dynamic contrast ratio of the device's screen. This property is applicable only for TVs.
		/// </summary>
		IAspectPropertyValue<string> DynamicContrastRatio { get; }
		/// <summary>
		/// Indicates the annual energy consumption of the device per year in kWh. This property is applicable only for TVs.
		/// </summary>
		IAspectPropertyValue<int> EnergyConsumptionPerYear { get; }
		/// <summary>
		/// Indicates the maximum amount of memory in gigabytes (GB) the expansion slot of the device can support.
		/// </summary>
		IAspectPropertyValue<int> ExpansionSlotMaxSize { get; }
		/// <summary>
		/// Indicates the expansion slot type the device can support.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> ExpansionSlotType { get; }
		/// <summary>
		/// Indicates if the browser supports the Fetch API.
		/// </summary>
		IAspectPropertyValue<bool> Fetch { get; }
		/// <summary>
		/// Indicates if the browser supports file reading with events to show progress and errors.
		/// </summary>
		IAspectPropertyValue<bool> FileReader { get; }
		/// <summary>
		/// Indicates if the browser allows Blobs to be saved to client machines with events to show progress and errors. The End-User may opt to decline these files.
		/// </summary>
		IAspectPropertyValue<bool> FileSaver { get; }
		/// <summary>
		/// Indicates if the browser allows files to be saved to client machines with events to show progress and errors. The End-User may opt to decline these files.
		/// </summary>
		IAspectPropertyValue<bool> FileWriter { get; }
		/// <summary>
		/// Indicates if the browser supports the 'FormData' object. This property also refers to XMLHttpRequest. If the browser supports 'xhr2', the 'FormData' element will be also supported. 
		/// </summary>
		IAspectPropertyValue<bool> FormData { get; }
		/// <summary>
		/// Indicates the list of frequency bands supported by the device.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> FrequencyBands { get; }
		/// <summary>
		/// Indicates the resolution of the device's front camera in megapixels. For a device that has a rotating camera the same value is returned for front and back megapixels' properties.
		/// </summary>
		IAspectPropertyValue<double> FrontCameraMegaPixels { get; }
		/// <summary>
		/// Indicates if the browser supports requests from a video or canvas element to be displayed in full-screen mode.
		/// </summary>
		IAspectPropertyValue<bool> Fullscreen { get; }
		/// <summary>
		/// Indicates if the browser supports a feature to acquire the geographical location. For information on which GeoLoc API the browser supports, refer to another property called JavaScriptPreferredGeoLocApi.
		/// </summary>
		IAspectPropertyValue<bool> GeoLocation { get; }
		/// <summary>
		/// Indicates the official name of the graphical chip within the SoC.
		/// </summary>
		IAspectPropertyValue<string> GPU { get; }
		/// <summary>
		/// Indicates the Semiconductor Company that designed the GPU.
		/// </summary>
		IAspectPropertyValue<string> GPUDesigner { get; }
		/// <summary>
		/// Refers to the list of audio codecs supported for decoding by a Chipset. An audio codec is a program used to playback digital audio files. The values of this property are the codec's common name.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareAudioCodecsDecode { get; }
		/// <summary>
		/// Refers to the list of audio codecs supported for encoding by a Chipset. An audio codec is a program used to capture digital audio files. The values of this property are the codec's common name.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareAudioCodecsEncode { get; }
		/// <summary>
		/// Indicates the carrier when the device is sold by the HardwareVendor on a single carrier or as indicated via device User-Agent.
		/// </summary>
		IAspectPropertyValue<string> HardwareCarrier { get; }
		/// <summary>
		/// Indicates the name of a group of devices that only differ by model or region but are marketed under the same name, e.g. Galaxy Tab S 10.5.
		/// </summary>
		IAspectPropertyValue<string> HardwareFamily { get; }
		/// <summary>
		/// A list of images associated with the device. The string contains the caption, followed by the full image URL separated with a tab character.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareImages { get; }
		/// <summary>
		/// Indicates the model name or number used primarily by the hardware vendor to identify the device, e.g.SM-T805S. When a model identifier is not available the HardwareName will be used.
		/// </summary>
		IAspectPropertyValue<string> HardwareModel { get; }
		/// <summary>
		/// Indicates all model numbers used by the hardware vendor to identify the device. This property compliments 'HardwareModel', e.g. Hardware Model Variants A1660 and A1778 correlate to the Hardware Model - iPhone 7.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareModelVariants { get; }
		/// <summary>
		/// Indicates the common marketing names associated with the device, e.g. Xperia Z5.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareName { get; }
		/// <summary>
		/// Indicates the source of the profile's specifications. This property will return 'Manufacturer' value if the profile data was obtained from the manufacturer of the device or the device itself. This property will return 'Authoritative' value if the profile data was not obtained from the manufacturer or the device itself but other third party sources (this may include retailers, social media, carriers, etc). This property will return 'Legacy' value if the profile data was obtained prior to 51degrees differentiating between Manufacturer and Authoritative. This property will return 'N/A' value if the profile data was not obtained due to unidentifiable User-Agent. The example profiles are: Generic Android Unknown, Unknown Tablet, etc.
		/// </summary>
		IAspectPropertyValue<string> HardwareProfileSource { get; }
		/// <summary>
		/// A measure of the popularity of this device model. All models are ordered by the number of events associated with that model that occurred in the sampling period. The device with the most events is ranked 1, the second 2 and so on. 
		/// </summary>
		IAspectPropertyValue<int> HardwareRank { get; }
		/// <summary>
		/// Indicates the name of the company that manufactures the device or primarily sells it, e.g. Samsung.
		/// </summary>
		IAspectPropertyValue<string> HardwareVendor { get; }
		/// <summary>
		/// Refers to the list of video codecs supported for decoding by a Chipset. An video codec is a program used to playback digital video files. The values of this property are the codec's common name. 
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareVideoCodecsDecode { get; }
		/// <summary>
		/// Refers to the list of video codecs supported for encoding by a Chipset. An video codec is a program used to capture digital video files. The values of this property are the codec's common name. 
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> HardwareVideoCodecsEncode { get; }
		/// <summary>
		/// Indicates if the device has a camera capable of taking 3D images.
		/// </summary>
		IAspectPropertyValue<bool> Has3DCamera { get; }
		/// <summary>
		/// Indicates if the device has a screen capable of displaying 3D images.
		/// </summary>
		IAspectPropertyValue<bool> Has3DScreen { get; }
		/// <summary>
		/// Indicates if the device has a camera.
		/// </summary>
		IAspectPropertyValue<bool> HasCamera { get; }
		/// <summary>
		/// Indicates if the device has a click wheel such as found on Apple iPod devices.
		/// </summary>
		IAspectPropertyValue<bool> HasClickWheel { get; }
		/// <summary>
		/// Indicates if the device has a physical numeric keypad.
		/// </summary>
		IAspectPropertyValue<bool> HasKeypad { get; }
		/// <summary>
		/// Indicates if the device has embedded NFC (Near Field Communication) wireless technology.
		/// </summary>
		IAspectPropertyValue<bool> HasNFC { get; }
		/// <summary>
		/// Indicates if the device has a physical qwerty keyboard.
		/// </summary>
		IAspectPropertyValue<bool> HasQwertyPad { get; }
		/// <summary>
		/// Indicates if the device has a removable battery. This property is not applicable for devices that do not have batteries. Unless otherwise stated this property will return a 'False' value for tablets.
		/// </summary>
		IAspectPropertyValue<bool> HasRemovableBattery { get; }
		/// <summary>
		/// Indicates if the device has a touch screen. This property will return 'False' for a device that does not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<bool> HasTouchScreen { get; }
		/// <summary>
		/// Indicates if the device has a trackpad or trackball. Examples of devices that support this property are the Nexus One and Blackberry Curve.
		/// </summary>
		IAspectPropertyValue<bool> HasTrackPad { get; }
		/// <summary>
		/// Indicates if the device has a virtual qwerty keyboard capability.
		/// </summary>
		IAspectPropertyValue<bool> HasVirtualQwerty { get; }
		/// <summary>
		/// Indicates if the browser stores the session history for a web page that contains the URLs visited by the browser's user.
		/// </summary>
		IAspectPropertyValue<bool> History { get; }
		/// <summary>
		/// Indicates if the browser is able to use media inputs, e.g. webcam and microphone, in a script and as an input for forms, e.g. '&lt;input type="file" accept="image/*" id="capture"&gt;' would prompt image- capturing software to open.
		/// </summary>
		IAspectPropertyValue<bool> HtmlMediaCapture { get; }
		/// <summary>
		/// Indicates if the browser supports the new markup in HTML 5 that also refers to 'New Semantic Elements' such as <![CDATA[<header>, <nav>, <section>, <aside>,<footer>]]> etc.
		/// </summary>
		IAspectPropertyValue<bool> Html5 { get; }
		/// <summary>
		/// Lists what audio formats, if any, the browser supports using the HTML5 <![CDATA[<audio>]]> tag.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> Html5Audio { get; }
		/// <summary>
		/// Lists what video formats, if any, the browser supports using the HTLM5 <![CDATA[<video>]]> tag.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> Html5Video { get; }
		/// <summary>
		/// Refers to the latest version of HyperText Markup Language (HTML) supported by the browser.
		/// </summary>
		IAspectPropertyValue<double> HtmlVersion { get; }
		/// <summary>
		/// Indicates if the browser supports HTTP version 2.
		/// </summary>
		IAspectPropertyValue<bool> Http2 { get; }
		/// <summary>
		/// Indicates if the browser supports HTTP Live Streaming, also known as HLS.
		/// </summary>
		IAspectPropertyValue<string> HttpLiveStreaming { get; }
		/// <summary>
		/// Indicates if the browser supports the 'Iframe' element, used to embed another document within a current HTML document.
		/// </summary>
		IAspectPropertyValue<bool> Iframe { get; }
		/// <summary>
		/// Indicates if the browser supports an indexed local database.
		/// </summary>
		IAspectPropertyValue<bool> IndexedDB { get; }
		/// <summary>
		/// Indicates the internal persistent storage (ROM capacity) options the device can be supplied with in gigabytes (GB), including the device's Operating System and bundled applications. This could also be referred to as "Electrically Erasable Programmable Read-Only Memory (EEPROM)" or "Non Volatile Random Access Memory (NVRAM)". If no variants are found, then the value returned will be the same as "MaxInternalStorage".
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> InternalStorageVariants { get; }
		/// <summary>
		/// Indicates if a web page is accessed through a VR headset.
		/// </summary>
		IAspectPropertyValue<bool> InVRMode { get; }
		/// <summary>
		/// Indicates if the device is primarily a game console, such as an Xbox or Playstation.
		/// </summary>
		IAspectPropertyValue<bool> IsConsole { get; }
		/// <summary>
		/// Indicates if the source of the web traffic identifies itself as operating without human interaction for the purpose of monitoring the availability or performance of a web site, retrieving a response for inclusion in a search engine or is requesting structured data such as via an API. Such sources are often referred to as crawlers, bots, robots, spiders, probes, monitors or HTTP services among other terms. Where the source pretends to be a device operating with human interaction, such as a smartphone or tablet, this property will return, 'False'.
		/// </summary>
		IAspectPropertyValue<bool> IsCrawler { get; }
		/// <summary>
		/// Indicates if the browser may be optimised for low bandwidth. A true value indicates the browser supports a feature that can improve performance on low bandwidth connections, either via the removal of elements, features, a proxy or other methods.
		/// </summary>
		IAspectPropertyValue<bool> IsDataMinimising { get; }
		/// <summary>
		/// Indicates if the application is an email browser (Outlook, Gmail, YahooMail, etc.) that is primarily used to access and manage emails (usually from mobile devices).
		/// </summary>
		IAspectPropertyValue<bool> IsEmailBrowser { get; }
		/// <summary>
		/// Indicates if the mobile device accessing a web page emulates a desktop computer. This property is not applicable for desktops, media hubs, TVs and consoles.
		/// </summary>
		IAspectPropertyValue<bool> IsEmulatingDesktop { get; }
		/// <summary>
		/// Indicates a browser that does not correctly identify the physical hardware device and instead reports an emulated device.
		/// </summary>
		IAspectPropertyValue<bool> IsEmulatingDevice { get; }
		/// <summary>
		/// Indicates if the device is primarily advertised as an e-reader. If the device type is EReader then the device is not classified as a tablet.
		/// </summary>
		IAspectPropertyValue<bool> IsEReader { get; }
		/// <summary>
		/// Indicates a profile which contains more than a single hardware device. When this is true all returned properties represent the default value or lowest given specification of all grouped devices. E.g. the profile representing unknown Windows 10 tablets will return true. Apple devices detected through JavascriptHardwareProfile that do not uniquely identify a device will also return true, and HardwareModelVariants will return a list of model numbers associated with that device group.
		/// </summary>
		IAspectPropertyValue<bool> IsHardwareGroup { get; }
		/// <summary>
		/// Indicates if the device is a media hub or set top box that requires an external display(s).
		/// </summary>
		IAspectPropertyValue<bool> IsMediaHub { get; }
		/// <summary>
		/// Indicates if the device's primary data connection is wireless and the device is designed to operate mostly by battery power (e.g. mobile phone, smartphone or tablet). This property does not indicate if the device is a mobile phone or not. Laptops are not classified as mobile devices under this definition and so 'IsMobile' will be 'False'.
		/// </summary>
		IAspectPropertyValue<bool> IsMobile { get; }
		/// <summary>
		/// Indicates whether the device screen is foldable or not. If the device does not have a screen or the screen is not foldable, 'False' is returned.
		/// </summary>
		IAspectPropertyValue<bool> IsScreenFoldable { get; }
		/// <summary>
		/// Indicates if the device is a mobile with a screen size less than 2.5 inches even where the device is marketed as a Smartphone.
		/// </summary>
		IAspectPropertyValue<bool> IsSmallScreen { get; }
		/// <summary>
		/// Indicates whether the device can make and receive phone calls, has a screen size greater than or equal to 2.5 inches, runs a modern operating system (Android, iOS, Windows Phone, BlackBerry etc.), is not designed to be a wearable technology and is marketed by the vendor as a Smartphone.
		/// </summary>
		IAspectPropertyValue<bool> IsSmartPhone { get; }
		/// <summary>
		/// Indicates if the device is a web enabled computerised wristwatch with other capabilities beyond timekeeping, such as push notifications. It runs on a Smart Operating System i.e. Android, WatchOS, Tizen, Ubuntu Touch and is designed to be wearable technology.
		/// </summary>
		IAspectPropertyValue<bool> IsSmartWatch { get; }
		/// <summary>
		/// Indicates if the device is primarily marketed as a tablet or phablet and has a screen size equal to or greater than 7 inches.
		/// </summary>
		IAspectPropertyValue<bool> IsTablet { get; }
		/// <summary>
		/// Indicates if the device is a TV running on a smart operating system e.g. Android.
		/// </summary>
		IAspectPropertyValue<bool> IsTv { get; }
		/// <summary>
		/// Indicates if a web page is accessed from an application whose main function is not browsing the World Wide Web or managing emails, e.g. the Facebook App. The application must be downloaded and installed onto the device from an app marketplace such as Apple's App Store or the Google Play Store, or via a third party as an .apk file or similar. This property will return a 'False' value for mobile browsers such as Chrome Mobile or email browsers (such as Hotmail).
		/// </summary>
		IAspectPropertyValue<bool> IsWebApp { get; }
		/// <summary>
		/// The number of iterations carried out in order to find a match. This is the number of nodes in the graph which have been visited.
		/// </summary>
		IAspectPropertyValue<int> Iterations { get; }
		/// <summary>
		/// Indicates if the browser supports JavaScript.
		/// </summary>
		IAspectPropertyValue<bool> Javascript { get; }
		/// <summary>
		/// Indicates if the browser supports the JavaScript that can manipulate CSS on the browser's web page.
		/// </summary>
		IAspectPropertyValue<bool> JavascriptCanManipulateCSS { get; }
		/// <summary>
		/// Indicates if the browser supports the JavaScript that can manipulate the Document Object Model on the browser's web page.
		/// </summary>
		IAspectPropertyValue<bool> JavascriptCanManipulateDOM { get; }
		/// <summary>
		/// Indicates if the browser supports JavaScript that is able to access HTML elements from their ID using the getElementById method.
		/// </summary>
		IAspectPropertyValue<bool> JavascriptGetElementById { get; }
		/// <summary>
		/// Contains Javascript to get high entropy values.
		/// </summary>
		IAspectPropertyValue<JavaScript> JavascriptGetHighEntropyValues { get; }
		/// <summary>
		/// JavaScript that can override the profile found by the server using information on the client device. This property is applicable for Apple devices which do not provide information about the model in the User-Agent string.
		/// </summary>
		IAspectPropertyValue<JavaScript> JavascriptHardwareProfile { get; }
		/// <summary>
		/// Refers to the JavaScript snippet used to optimise images.
		/// </summary>
		IAspectPropertyValue<JavaScript> JavascriptImageOptimiser { get; }
		/// <summary>
		/// Indicates which GeoLoc API JavaScript the browser supports. If a browser supports a feature to acquire the user's geographical location, another property called 'GeoLocation' will be set to True.
		/// </summary>
		IAspectPropertyValue<string> JavascriptPreferredGeoLocApi { get; }
		/// <summary>
		/// Indicates if the browser allows registration of event listeners on event targets by using the addEventListener() method.
		/// </summary>
		IAspectPropertyValue<bool> JavascriptSupportsEventListener { get; }
		/// <summary>
		/// Indicates if the browser supports the JavaScript events 'onload', 'onclick' and 'onselect'. 
		/// </summary>
		IAspectPropertyValue<bool> JavascriptSupportsEvents { get; }
		/// <summary>
		/// Indicates if the browser supports the JavaScript that is able to insert HTML into a DIV tag.
		/// </summary>
		IAspectPropertyValue<bool> JavascriptSupportsInnerHtml { get; }
		/// <summary>
		/// Indicates which JavaScript version the browser uses. The number refers to JavaScript versioning, not ECMAscript or Jscript. If the browser doesn't support JavaScript then 'NotSupported' value is returned.
		/// </summary>
		IAspectPropertyValue<string> JavascriptVersion { get; }
		/// <summary>
		/// Indicates the browser supports JPEG 2000 image format.
		/// </summary>
		IAspectPropertyValue<bool> Jpeg2000 { get; }
		/// <summary>
		/// Refers to the grade of the level the device has with the jQuery Mobile Framework, as posted by jQuery.
		/// </summary>
		IAspectPropertyValue<string> jQueryMobileSupport { get; }
		/// <summary>
		/// Indicates if the browser supports the 'JSON' object. This property may need a vendor prefix, e.g. webkit, moz, etc.
		/// </summary>
		IAspectPropertyValue<bool> Json { get; }
		/// <summary>
		/// Refers to the name of the embedded technology the browser uses to display formatted content on the screen.
		/// </summary>
		IAspectPropertyValue<string> LayoutEngine { get; }
		/// <summary>
		/// Indicates if the browser supports the CSS-mask element that allows users to alter the visibility of an item by either partially or fully hiding the item.
		/// </summary>
		IAspectPropertyValue<bool> Masking { get; }
		/// <summary>
		/// Indicates the number of hash nodes matched within the evidence.
		/// </summary>
		IAspectPropertyValue<int> MatchedNodes { get; }
		/// <summary>
		/// Indicates the maximum amount of internal persistent storage (ROM capacity) with which the device is supplied in gigabytes (GB), including the space used by the device's Operating System and bundled applications. This could also be referred to as "Electrically Erasable Programmable Read-Only Memory (EEPROM)" or "Non Volatile Random Access Memory (NVRAM)". Where a device has different internal storage options, the largest option available is returned.
		/// </summary>
		IAspectPropertyValue<double> MaxInternalStorage { get; }
		/// <summary>
		/// Indicates the maximum number of "Universal Integrated Circuit Cards (UICC - more commonly known as, SIM)" the device can support including both removable and embedded. If the device doesn't support any UICC then a value of '0' is returned.
		/// </summary>
		IAspectPropertyValue<int> MaxNumberOfSIMCards { get; }
		/// <summary>
		/// Indicates the maximum standby time of the device in hours. This property is not applicable for a device without a battery.
		/// </summary>
		IAspectPropertyValue<int> MaxStandbyTime { get; }
		/// <summary>
		/// Indicates the maximum talk time of the device in minutes. This property is not applicable for a device that does not have a battery or support phone calls.
		/// </summary>
		IAspectPropertyValue<int> MaxTalkTime { get; }
		/// <summary>
		/// Indicates the maximum general usage time of the device in minutes. This property is not applicable for a device without a battery.
		/// </summary>
		IAspectPropertyValue<int> MaxUsageTime { get; }
		/// <summary>
		/// Indicates if the browser supports a meter element that represents a scalar measurement within a known range or fractional value. This property does not indicate whether the browser supports the progress bar indication. For this purpose, the progress property should be used.
		/// </summary>
		IAspectPropertyValue<bool> Meter { get; }
		/// <summary>
		/// The method used to determine the match result.
		/// </summary>
		IAspectPropertyValue<string> Method { get; }
		/// <summary>
		/// Indicates which version of Mobile Information Device Profile the device supports, used with Java ME and CLDC.
		/// </summary>
		IAspectPropertyValue<double> MIDP { get; }
		/// <summary>
		/// Refers to the 'Retail Branding' value returned for Android Google Play native applications, when the android.os.Build.BRAND javascript is used to display the class. This property is not applicable for hardware running on operating systems other than Android.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> NativeBrand { get; }
		/// <summary>
		/// Refers to the 'Device' value returned for Android Google Play native applications, when the android.os.Build.DEVICE javascript is used to display the class. This property is not applicable for hardware running on operating systems other than Android.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> NativeDevice { get; }
		/// <summary>
		/// Refers to the 'Model' value returned for Android Google Play native applications, when the android.os.Build.MODEL javascript is used to display the class. For Apple devices this property refers to the device identifier which appears in the native application from the developer usage log, for example 'iPad5,4'.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> NativeModel { get; }
		/// <summary>
		/// NativeName Refers to the 'Marketing Name' value that a device is registered with on the Google Play service. This property is not applicable for hardware running on operating systems other than Android.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> NativeName { get; }
		/// <summary>
		/// Indicates the name of the mobile operating system (iOS, Android) for which an application program has been developed to be used by a device.
		/// </summary>
		IAspectPropertyValue<string> NativePlatform { get; }
		/// <summary>
		/// Indicates the number of screens the device has. This property is not applicable for a device that does not have a screen.
		/// </summary>
		IAspectPropertyValue<int> NumberOfScreens { get; }
		/// <summary>
		/// Indicates the name of the company that manufactures the device.
		/// </summary>
		IAspectPropertyValue<string> OEM { get; }
		/// <summary>
		/// Indicates the power consumption of the device while switched on. This property is applicable only for TVs.
		/// </summary>
		IAspectPropertyValue<int> OnPowerConsumption { get; }
		/// <summary>
		/// The ratio of the resolution in physical pixels to the resolution in CSS pixels. This is approximated by screen resolution and screen size when the value is not known.
		/// </summary>
		IAspectPropertyValue<double> PixelRatio { get; }
		/// <summary>
		/// JavaScript that can override the property value found by the server using information on the client device. This property is applicable for browsers that support pixel ratio cookie.
		/// </summary>
		IAspectPropertyValue<JavaScript> PixelRatioJavascript { get; }
		/// <summary>
		/// Indicates the age in months of the operating system since the PlatformReleaseYear and PlatformReleaseMonth.
		/// </summary>
		IAspectPropertyValue<int> PlatformDiscontinuedAge { get; }
		/// <summary>
		/// The month in which further development for the platform version is stopped by the platform vendor. This occurs when a new stable version of the platform is released.
		/// </summary>
		IAspectPropertyValue<string> PlatformDiscontinuedMonth { get; }
		/// <summary>
		/// The year in which further development for the platform version is stopped by the platform vendor. This occurs when a new stable version of the platform is released.
		/// </summary>
		IAspectPropertyValue<int> PlatformDiscontinuedYear { get; }
		/// <summary>
		/// Indicates the name of the operating system the device is using.
		/// </summary>
		IAspectPropertyValue<string> PlatformName { get; }
		/// <summary>
		/// Indicates the age in months of the operating system since the PlatformPreviewYear and PlatformPreviewMonth.
		/// </summary>
		IAspectPropertyValue<int> PlatformPreviewAge { get; }
		/// <summary>
		/// The month in which the platform version was originally released as a Beta/Developer version by the platform vendor. This is before it is officially released as a stable version, to ensure wider testing by the community can take place.
		/// </summary>
		IAspectPropertyValue<string> PlatformPreviewMonth { get; }
		/// <summary>
		/// The year in which the platform version was originally released as a Beta/Developer version by the platform vendor. This is before it is officially released as a stable version, to ensure wider testing by the community can take place.
		/// </summary>
		IAspectPropertyValue<int> PlatformPreviewYear { get; }
		/// <summary>
		/// A measure of the popularity of this software platform (i.e. OS and version). All platforms are ordered by the number of events associated with that platform that occurred in the sampling period. The platform with the most events is ranked 1, the second 2 and so on.
		/// </summary>
		IAspectPropertyValue<int> PlatformRank { get; }
		/// <summary>
		/// Indicates the age in months of the operating system since the PlatformReleaseYear and PlatformReleaseMonth.
		/// </summary>
		IAspectPropertyValue<int> PlatformReleaseAge { get; }
		/// <summary>
		/// The month in which the platform version was officially released to users by the platform vendor. This version is called the stable version as any bugs or difficulties highlighted in the Beta/Developer version will have been fixed for this release.
		/// </summary>
		IAspectPropertyValue<string> PlatformReleaseMonth { get; }
		/// <summary>
		/// The year in which the platform version was officially released to users by the platform vendor. This version is called the stable version as any bugs or difficulties highlighted in the Beta/Developer Version will have been fixed for this release.
		/// </summary>
		IAspectPropertyValue<int> PlatformReleaseYear { get; }
		/// <summary>
		/// Indicates the name of the company that developed the operating system.
		/// </summary>
		IAspectPropertyValue<string> PlatformVendor { get; }
		/// <summary>
		/// Indicates the version or subversion of the software platform.
		/// </summary>
		IAspectPropertyValue<string> PlatformVersion { get; }
		/// <summary>
		/// Indicates if the browser supports messages between different documents.
		/// </summary>
		IAspectPropertyValue<bool> PostMessage { get; }
		/// <summary>
		/// Indicates if the browser can prefetch resources without executing them.
		/// </summary>
		IAspectPropertyValue<bool> Preload { get; }
		/// <summary>
		/// Indicates a price range describing the recommended retail price of the device at the date of release, inclusive of tax (where applicable).  Prices are in United States Dollars (USD); if the price is not originally in USD it will be converted to USD using the relevant exchange rate at the time of launch. Prices are for the SIM-free version of the device (if applicable). In cases where there are several versions of the same model of the device, the price will reflect the device that was used to populate the specifications.
		/// </summary>
		IAspectPropertyValue<string> PriceBand { get; }
		/// <summary>
		/// Indicates if the browser supports progress reports, such as with HTTP requests. The progress element can be used to display the progress of the task. This property doesn't represent a scalar measurement. If the browser supports a gauge, the meter property should be used.
		/// </summary>
		IAspectPropertyValue<bool> Progress { get; }
		/// <summary>
		/// Indicates the level of support for the Promise object. The Promise object represents the eventual completion (or failure) of an asynchronous operation, and its resulting value.
		/// </summary>
		IAspectPropertyValue<string> Promise { get; }
		/// <summary>
		/// Indicates if the browser supports simple dialogues (window.alert, window.confirm and window.prompt).
		/// </summary>
		IAspectPropertyValue<bool> Prompts { get; }
		/// <summary>
		/// Indicates the number of frames per second the television can display in Hertz. This property is applicable only for TVs.
		/// </summary>
		IAspectPropertyValue<int> RefreshRate { get; }
		/// <summary>
		/// Indicates the age in months of the device since the ReleaseYear and ReleaseMonth.
		/// </summary>
		IAspectPropertyValue<int> ReleaseAge { get; }
		/// <summary>
		/// Indicates the month in which the device was released or the month in which the device was first seen by 51Degrees (if the release date cannot be identified).
		/// </summary>
		IAspectPropertyValue<string> ReleaseMonth { get; }
		/// <summary>
		/// Indicates the year in which the device was released or the year in which the device was first seen by 51Degrees (if the release date cannot be identified).
		/// </summary>
		IAspectPropertyValue<int> ReleaseYear { get; }
		/// <summary>
		/// Indicates  the device's supported satellite navigation types.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SatelliteNavigationTypes { get; }
		/// <summary>
		/// Indicates the diagonal size of the device's screen in inches, to a maximum of two decimal points. Where screens have curved corners, the actual viewable area may be less.
		/// </summary>
		IAspectPropertyValue<double> ScreenInchesDiagonal { get; }
		/// <summary>
		/// Indicates the diagonal size of the device's screen in inches rounded to the nearest whole number. This property will return the value 'Unknown' for desktop or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<int> ScreenInchesDiagonalRounded { get; }
		/// <summary>
		/// Refers to the height of the device's screen in inches. This property will return 'Unknown' for desktops or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<double> ScreenInchesHeight { get; }
		/// <summary>
		/// Indicates the area of the device's screen in square inches rounded to the nearest whole number. This property will return the value 'Unknown' for desktop or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<int> ScreenInchesSquare { get; }
		/// <summary>
		/// Refers to the width of the device's screen in inches. This property will return the value 'Unknown' for desktop or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<double> ScreenInchesWidth { get; }
		/// <summary>
		/// Refers to the diagonal size of the screen of the device in millimetres. This property will return 'Unknown' for desktops or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<double> ScreenMMDiagonal { get; }
		/// <summary>
		/// Indicate the diagonal size of the device's screen in millimetres rounded to the nearest whole number. This property will return the value 'Unknown' for desktop or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<int> ScreenMMDiagonalRounded { get; }
		/// <summary>
		/// Refers to the screen height of the device in millimetres. This property will return 'Unknown' for desktops or for devices which do not have an integrated screen. For devices such as tablets or TV which are predominantly used in landscape mode, the screen height will be the smaller value compared to the screen width.
		/// </summary>
		IAspectPropertyValue<double> ScreenMMHeight { get; }
		/// <summary>
		/// Indicates the area of the device's screen in square millimetres rounded to the nearest whole number. This property will return the value  'Unknown' for desktop or for devices which do not have an integrated screen.
		/// </summary>
		IAspectPropertyValue<int> ScreenMMSquare { get; }
		/// <summary>
		/// Refers to the screen width of the device in millimetres. This property will return 'Unknown' for desktops or for devices which do not have an integrated screen. For devices such as tablets or TV which are predominantly used in landscape mode, the screen height will be the smaller value compared to the screen width.
		/// </summary>
		IAspectPropertyValue<double> ScreenMMWidth { get; }
		/// <summary>
		/// Indicates the height of the device's screen in pixels.This property is not applicable for a device that does not have a screen. For devices such as tablets or TV which are predominantly used in landscape mode, the pixel height will be the smaller value compared to the pixel width.
		/// </summary>
		IAspectPropertyValue<int> ScreenPixelsHeight { get; }
		/// <summary>
		/// JavaScript that can override the property value found by the server using information on the client device. This property is applicable for browsers that support screen pixels height cookie.
		/// </summary>
		IAspectPropertyValue<JavaScript> ScreenPixelsHeightJavaScript { get; }
		/// <summary>
		/// Indicates the width of the device's screen in pixels. This property is not applicable for a device that does not have a screen. For devices such as tablets or TV which are predominantly used in landscape mode, the pixel width will be the larger value compared to the pixel height.
		/// </summary>
		IAspectPropertyValue<int> ScreenPixelsWidth { get; }
		/// <summary>
		/// JavaScript that can override the property value found by the server using information on the client device. This property is applicable for browsers that support screen pixels width cookie. 
		/// </summary>
		IAspectPropertyValue<JavaScript> ScreenPixelsWidthJavaScript { get; }
		/// <summary>
		/// Indicates the screen type of the device. This property is not applicable for a device that does not have an integrated screen, e.g. a media hub. If the device manufacturer or vendor does not specify what the screen type of the device is then it is assumed the device has an LCD screen.
		/// </summary>
		IAspectPropertyValue<string> ScreenType { get; }
		/// <summary>
		/// Indicates the resolution of the device's second back camera in megapixels.
		/// </summary>
		IAspectPropertyValue<double> SecondBackCameraMegaPixels { get; }
		/// <summary>
		/// Indicates the resolution of the device's second front camera in megapixels.
		/// </summary>
		IAspectPropertyValue<double> SecondFrontCameraMegaPixels { get; }
		/// <summary>
		/// Indicates the diagonal size of the device's second screen in inches. This property is not applicable for a device that does not have a second screen.
		/// </summary>
		IAspectPropertyValue<double> SecondScreenInchesDiagonal { get; }
		/// <summary>
		/// Indicates the diagonal size of the device's second screen in inches rounded to the nearest whole number. This property will return the value 'N/A' for desktop or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<int> SecondScreenInchesDiagonalRounded { get; }
		/// <summary>
		/// Refers to the height of the device's second screen in inches. This property will return 'N/A' for desktops or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<double> SecondScreenInchesHeight { get; }
		/// <summary>
		/// Indicates the area of the device's second screen in square inches rounded to the nearest whole number. This property will return the value 'N/A' for desktop or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<int> SecondScreenInchesSquare { get; }
		/// <summary>
		/// Refers to the width of the device's second screen in inches. This property will return the value 'N/A' for desktop or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<double> SecondScreenInchesWidth { get; }
		/// <summary>
		/// Refers to the diagonal size of the second screen of the device in millimetres. This property will return 'N/A' for desktops or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<double> SecondScreenMMDiagonal { get; }
		/// <summary>
		/// Indicate the diagonal size of the device's second screen in millimetres rounded to the nearest whole number. This property will return the value 'N/A' for desktop or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<int> SecondScreenMMDiagonalRounded { get; }
		/// <summary>
		/// Refers to the second screen height of the device in millimetres. This property will return 'N/A' for desktops or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<double> SecondScreenMMHeight { get; }
		/// <summary>
		/// Indicates the area of the device's second screen in square millimetres rounded to the nearest whole number. This property will return the value  'N/A' for desktop or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<int> SecondScreenMMSquare { get; }
		/// <summary>
		/// Refers to the second screen width of the device in millimetres. This property will return 'N/A' for desktops or for devices which do not have a second screen.
		/// </summary>
		IAspectPropertyValue<double> SecondScreenMMWidth { get; }
		/// <summary>
		/// Indicates the height of the device's second screen in pixels. This property is not applicable for a device that does not have a second screen.
		/// </summary>
		IAspectPropertyValue<int> SecondScreenPixelsHeight { get; }
		/// <summary>
		/// Indicates the width of the device's second screen in pixels. This property is not applicable for a device that does not have a second screen.
		/// </summary>
		IAspectPropertyValue<int> SecondScreenPixelsWidth { get; }
		/// <summary>
		/// Indicates if the browser supports the querySelector() method that returns the first element matching a specified CSS selector(s) in the document.
		/// </summary>
		IAspectPropertyValue<bool> Selector { get; }
		/// <summary>
		/// Contains the Accept-CH HTTP header values to add to the HTTP response for the browser component. UACH values Sec-CH-UA, and Sec-CH-UA-Full-Version are relevant. The default value is Unknown if the browser does not fully support UACH.
		/// </summary>
		IAspectPropertyValue<string> SetHeaderBrowserAcceptCH { get; }
		/// <summary>
		/// Contains the Accept-CH HTTP header values to add to the HTTP response for the hardware component. UACH values Sec-CH-UA-Model, and Sec-CH-UA-Mobile are relevant. The default value is Unknown if the browser does not fully support UACH.
		/// </summary>
		IAspectPropertyValue<string> SetHeaderHardwareAcceptCH { get; }
		/// <summary>
		/// Contains the Accept-CH HTTP header values to add to the HTTP response for the platform component. UACH values Sec-CH-UA-Platform, and Sec-CH-UA-Platform-Version are relevant. The default value is Unknown if the browser does not fully support UACH.
		/// </summary>
		IAspectPropertyValue<string> SetHeaderPlatformAcceptCH { get; }
		/// <summary>
		/// Indicates the primary marketing name of the System on Chip (chipset) which includes the CPU, GPU and modem. e.g. Snapdragon S4
		/// </summary>
		IAspectPropertyValue<string> SoC { get; }
		/// <summary>
		/// Indicates the Semiconductor Company that designed the System on Chip (chipset) e.g. Qualcomm, Intel or Mediatek.
		/// </summary>
		IAspectPropertyValue<string> SoCDesigner { get; }
		/// <summary>
		/// Indicates the official model of the System on Chip (chipset) e.g. MSM8625, MT8312.
		/// </summary>
		IAspectPropertyValue<string> SoCModel { get; }
		/// <summary>
		/// Refers to the list of audio codecs supported by an operating system. This list of codecs is supported for playback on a  basic software installation. The values of this property are the codec's common name.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SoftwareAudioCodecsDecode { get; }
		/// <summary>
		/// Refers to the list of audio codecs supported by an operating system. This list of codecs is supported for capture on a basic software installation. The values of this property are the codec's common name.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SoftwareAudioCodecsEncode { get; }
		/// <summary>
		/// Refers to the list of video codecs supported by an operating system. This list of codecs is supported for playback on a  basic software installation. The values of this property are the codec's common name.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SoftwareVideoCodecsDecode { get; }
		/// <summary>
		/// Refers to the list of video codecs supported by an operating system. This list of codecs is supported for capture on a basic software installation. The values of this property are the codec's common name.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SoftwareVideoCodecsEncode { get; }
		/// <summary>
		/// The Specific Absorbtion Rate (SAR) is a measure of the rate at which energy is absorbed by the human body when exposed by a radio frequency electromagnetic field. This property contains values in Watts per Kilogram (W/kg) in accordance with the European Committee for Electrotechnical Standardization (CENELEC).
		/// </summary>
		IAspectPropertyValue<double> SpecificAbsorbtionRateEU { get; }
		/// <summary>
		/// The Specific Absorbtion Rate (SAR) is a measure of the rate at which energy is absorbed by the human body when exposed by a radio frequency electromagnetic field. This property contains values in Watts per Kilogram (W/kg) in accordance with the Federal Communications Commission (FCC).
		/// </summary>
		IAspectPropertyValue<double> SpecificAbsorbtionRateUS { get; }
		/// <summary>
		/// A list of MIME types the device can stream. The list does not include MIME types that are only supported through the use of 3rd party applications.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> StreamingAccept { get; }
		/// <summary>
		/// Refers to the suggested optimum height of a button in millimetres. Ensures the button is touchable on a touch screen and not too large on a non-touch screen. Assumes the actual device DPI (Dots Per Inch) is being used. 
		/// </summary>
		IAspectPropertyValue<double> SuggestedImageButtonHeightMms { get; }
		/// <summary>
		/// Refers to the suggested optimum height of a button in millimetres. Ensures the button is touchable on a touch screen and not too large on a non-touch screen. 
		/// </summary>
		IAspectPropertyValue<double> SuggestedImageButtonHeightPixels { get; }
		/// <summary>
		/// Refers to the suggested optimum height of a hyperlink in pixels. Ensures the link is touchable on a touch screen and not too large on a non-touch screen. Assumes the actual device DPI is being used.
		/// </summary>
		IAspectPropertyValue<double> SuggestedLinkSizePixels { get; }
		/// <summary>
		/// Refers to the suggested optimum height of a hyperlink in points. Ensures the link is touchable on a touch screen and not too large on a non-touch screen. 
		/// </summary>
		IAspectPropertyValue<double> SuggestedLinkSizePoints { get; }
		/// <summary>
		/// Indicates the list of wireless data technologies supported by the device, including Bluetooth and Wi-Fi. For example, 4G cellular network technologies includes 'LTE' (Long Term Evolution), and 5G technologies includes 'NR' (New Radio). If the device supports phone calls, the SMS value is also returned.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SupportedBearers { get; }
		/// <summary>
		/// Indicates the highest version of Bluetooth the device supports.
		/// </summary>
		IAspectPropertyValue<string> SupportedBluetoothVersion { get; }
		/// <summary>
		/// Indicates the list of features the device's camera supports.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SupportedCameraFeatures { get; }
		/// <summary>
		/// Indicates the list of charger types supported by the device. For devices that operate via mains power only, e.g. TVs, MediaHubs (which technically aren't being charged) this property is not applicable.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SupportedChargerTypes { get; }
		/// <summary>
		/// Indicates the list of input and output communications the device can support, for example 3.5mm audio jack, micro-USB etc.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SupportedIO { get; }
		/// <summary>
		/// Indicates the list of sensors supported by the device. This property may be not applicable for devices without sensors, such as most feature phones and media hubs.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SupportedSensorTypes { get; }
		/// <summary>
		/// Indicates whether the "Universal Integrated Circuit Card (UICC - more commonly known as, SIM)" is removable or embedded. If removable, the form factor of the UICC is returned.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> SupportedSIMCardTypes { get; }
		/// <summary>
		/// Indicates if the device supports 24p; a video format that operates at 24 frames per second. This property is applicable only for TVs.
		/// </summary>
		IAspectPropertyValue<bool> Supports24p { get; }
		/// <summary>
		/// Indicates if the device can receive and make telephone calls using available bearers without any additional software such as VoIP. Devices that support voice calls do not necessarily support phone calls.
		/// </summary>
		IAspectPropertyValue<bool> SupportsPhoneCalls { get; }
		/// <summary>
		/// Indicates if the browser supports TLS or SSL, essential for secure protocols such as HTTPS.
		/// </summary>
		IAspectPropertyValue<bool> SupportsTlsSsl { get; }
		/// <summary>
		/// Indicates if the browser supports WebGL technology to generate hardware-accelerated 3D graphics.
		/// </summary>
		IAspectPropertyValue<bool> SupportsWebGL { get; }
		/// <summary>
		/// Indicates if the device supports Wireless Display Technology. This property is only applicable for TVs.
		/// </summary>
		IAspectPropertyValue<bool> SupportsWiDi { get; }
		/// <summary>
		/// Indicates if the browser supports SVG (scalable vector graphics), useful for 2D animations and applications where all objects within the SVG can be accessed via the DOM and can have assigned event listener elements.
		/// </summary>
		IAspectPropertyValue<bool> Svg { get; }
		/// <summary>
		/// Indicates the Type Allocation Code (TAC) for devices supporting GSM/3GPP networks which come from multiple sources. This property will return 'N/A' if we cannot determine the device TAC authenticy.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> TAC { get; }
		/// <summary>
		/// Indicates if the browser supports the method of registering and interpreting finder (or stylus) activity on touch screens or trackpads.
		/// </summary>
		IAspectPropertyValue<bool> TouchEvents { get; }
		/// <summary>
		/// Indicates if the browser supports a method of tracking text being played with media, e.g. subtitles and captions.
		/// </summary>
		IAspectPropertyValue<bool> Track { get; }
		/// <summary>
		/// The matched User-Agents.
		/// </summary>
		IAspectPropertyValue<IReadOnlyList<string>> UserAgents { get; }
		/// <summary>
		/// Indicates if the browser supports the 'Video' element for playing videos on web pages without requiring a plug-in.
		/// </summary>
		IAspectPropertyValue<bool> Video { get; }
		/// <summary>
		/// Indicates if the browser supports Viewport, to give control over view for different screen sizes and resolutions of devices accessing a website.
		/// </summary>
		IAspectPropertyValue<bool> Viewport { get; }
		/// <summary>
		/// Indicates if the browser supports the WebP image format.
		/// </summary>
		IAspectPropertyValue<bool> WebP { get; }
		/// <summary>
		/// Indicates if the browser supports background workers in JavaScript.
		/// </summary>
		IAspectPropertyValue<bool> WebWorkers { get; }
		/// <summary>
		/// Indicates the weight of the device with battery in grams.
		/// </summary>
		IAspectPropertyValue<double> WeightWithBattery { get; }
		/// <summary>
		/// Indicates the weight of the device without battery in grams.
		/// </summary>
		IAspectPropertyValue<double> WeightWithoutBattery { get; }
		/// <summary>
		/// Indicates if the browser supports client-to-server communication with XmlHttpRequests. If the browser supports 'Xhr2' will also support 'DataForm' element. This property may need a vendor prefix, e.g. webkit, moz, etc.
		/// </summary>
		IAspectPropertyValue<bool> Xhr2 { get; }
	}
}
