name: Nightly Publish Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: false
        type: boolean
        description: Dry Run
  workflow_run:
    workflows: [Nightly PRs to Main]
    types: [completed]

jobs:
  # Run the common workflow to test and publish the main branch
  Nightly_Publish_Main:
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish-main.yml@dotnet-debug
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
      common-ci-ref: dotnet-debug
      build-platform: windows-latest
    secrets: 
      token: ${{ secrets.ACCESS_TOKEN }}
      ApiKey: ${{ secrets.NUGET_API_KEY }}
      CodeSigningKeyVaultUrl: ${{ secrets.CODE_SIGNING_KEY_VAULT_URL }}
      CodeSigningKeyVaultClientId: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_ID }}
      CodeSigningKeyVaultTenantId: ${{ secrets.CODE_SIGNING_KEY_VAULT_TENANT_ID }}
      CodeSigningKeyVaultClientSecret: ${{ secrets.CODE_SIGNING_KEY_VAULT_CLIENT_SECRET }}
      CodeSigningKeyVaultCertificateName: ${{ secrets.CODE_SIGNING_KEY_VAULT_CERTIFICATE_NAME }}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      DeviceDetectionUrl: ${{ secrets.DEVICE_DETECTION_URL }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      AcceptCHBrowserKey: ${{ secrets.ACCEPTCH_BROWSER_KEY}}
      AcceptCHHardwareKey: ${{ secrets.ACCEPTCH_HARDWARE_KEY}}
      AcceptCHPlatformKey: ${{ secrets.ACCEPTCH_PLATFORM_KEY}}
      AcceptCHNoneKey: ${{ secrets.ACCEPTCH_NONE_KEY}}
